//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using Singleton;

namespace Menu
{
	public class YouAreDeadHandler : MonoBehaviour
	{
		public GameObject Panel 
		{
			get { return _youAreDeadPanel; }
		}

		private GameObject _youAreDeadPanel;
		private Button _restartButton;
		private Button _exitButton;

		/// <summary>
		/// Start this instance.
		/// </summary>
		void Start()
		{
			_youAreDeadPanel = GameObject.Find("YouAreDeadPanel");

			_restartButton = _youAreDeadPanel.GetComponentsInChildren<Button>().First(btn => btn.name == "RestartButton");
			_exitButton = _youAreDeadPanel.GetComponentsInChildren<Button>().First(btn => btn.name == "ExitButton");

			// This is a setup for a button that grabs the field value when pressed
			_restartButton.onClick.AddListener(() => RestartGame());
			_exitButton.onClick.AddListener(() => ExitGame());

			SwitchYouAreDeadPanel();
		}

		/// <summary>
		/// Handles the sub window.
		/// </summary>
		public void SwitchYouAreDeadPanel()
		{
			_youAreDeadPanel.SetActive(!_youAreDeadPanel.activeSelf);
			if (_youAreDeadPanel.activeSelf)
			{
				_youAreDeadPanel.transform.SetAsLastSibling();
			}
		}

		/// <summary>
		/// Adapts the worker speed.
		/// </summary>
		/// <param name="newValue">New value.</param>
		private void RestartGame()
		{
			PlayerSingleton.Instance.PlayerHealth = PlayerSingleton.Instance.TotalHealth;
			PrefabSingleton.Instance.LevelStartup.StartLevel();

			while(PrefabSingleton.Instance.ScreenFader.IsBlack)
			{
				PrefabSingleton.Instance.ScreenFader.RestartScene();
			}

            // TODO: Hier muss ein update auf PlayerUpdates._actualHealth hin, sonst wird man immer wieder den
            // schwarzen bildschirm kriegen... evtl. ein Reset()?
			PlayerSingleton.Instance.PlayerHealth = PlayerSingleton.Instance.TotalHealth;
			SwitchYouAreDeadPanel();
		}

		/// <summary>
		/// Adapts the worker speed.
		/// </summary>
		/// <param name="newValue">New value.</param>
		private void ExitGame()
		{

		}
	}
}