//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using System.Linq;
using Singleton;

namespace Singletons
{
	public class HelperSingleton
	{
		public string LastLoadedLevel {get; set;}

		private static HelperSingleton _instance;
		
		/// <summary>
		/// Gets instance
		/// </summary>
		public static HelperSingleton Instance
		{
			get
			{
				if (_instance == null) 
				{
					_instance = new HelperSingleton();
				}
				
				return _instance;
			}
		}

		/// <summary>
		/// Sets the cursor.
		/// </summary>
		/// <param name="newCursor">New cursor.</param>
		public GameObject GetTopMostGO(GameObject gameObject, bool getLastTagged)
		{
			if (gameObject == null)
			{
				return null;
			}

			GameObject intermediateResult = null;
			GameObject parent = gameObject;
			while (parent.transform.parent != null)
			{
				var newParent = parent.transform.parent.gameObject;

				if (getLastTagged && newParent.tag != "Untagged")
				{
					intermediateResult = newParent;
				}

				if (newParent.transform.position == Vector3.zero)
				{
					// This is only a container - we reached the end!
					return parent;
				}

				parent = newParent;
			}

			if (parent.tag == "Untagged" && getLastTagged)
			{
				// If we wanted to return the last tagged, return it.
				return intermediateResult != null 
					? intermediateResult
					: parent;
			}

			return parent;
		}
	
		/// <summary>
		/// Gets the GO which is the nearest to the player.
		/// </summary>
		/// <param name="">.</param>
		/// <param name="myPosition">My position.</param>
		public GameObject GetNearestGameObject(IEnumerable<GameObject> objects, Vector3 myPosition)
		{
			objects = objects.Distinct();
			Dictionary<GameObject, float> distanceToObject = new Dictionary<GameObject, float>();

			if (!objects.Any() || objects.All(ob => ob == null))
			{
				return null;
			}

			foreach (var go in objects)
			{
				distanceToObject.Add(go, (go.transform.position - myPosition).magnitude);
			}

			return distanceToObject.OrderBy(pair => pair.Value).First().Key;
		}

		/// <summary>
		/// Returns the center of the gameobject, using the collidor attached to the go. If no collidier is attached, transform.position is returned.
		/// </summary>
		/// <returns>The center of game object.</returns>
		/// <param name="gameObject">Game object.</param>
		public Vector3 GetCenterOfGameObject(GameObject gameObject)
		{
			var collidor = gameObject.GetComponent<Collider>();
			if (collidor != null)
			{
				return collidor.bounds.center;
			}

			return gameObject.transform.position;
		}

		/// <summary>
		/// Splits up.
		/// </summary>
		/// <returns>The up.</returns>
		/// <param name="splitUp">Split up.</param>
		public string SplitUp(string splitUp)
		{
			string output = String.Empty;
			foreach (char letter in splitUp)
			{
				if (Char.IsUpper(letter) && output.Length > 0)
					output += " " + letter;
				else
					output += letter;
			}

			return output;
		}

		/// <summary>
		/// Destroies the level.
		/// </summary>
		public void DestroyLevel()
		{
			// Destroy all old gameobjectz
			foreach (Transform item in PrefabSingleton.Instance.CeillingParent.transform)
			{
				GameObject.Destroy(item.gameObject)	;
			}
			foreach (Transform item in PrefabSingleton.Instance.LevelParent.transform)
			{
				GameObject.Destroy(item.gameObject)	;
			}
			foreach (Transform item in PrefabSingleton.Instance.LightsParent.transform)
			{
				GameObject.Destroy(item.gameObject)	;
			}
			foreach (Transform item in PrefabSingleton.Instance.PickupParent.transform)
			{
				GameObject.Destroy(item.gameObject)	;
			}
			foreach (Transform item in PrefabSingleton.Instance.StandBlockParent.transform)
			{
				GameObject.Destroy(item.gameObject)	;
			}
			
			// Destroy all Hearts
			var hearts = GameObject.FindGameObjectsWithTag("Heart");
			foreach (var heart in hearts) 
			{
				GameObject.Destroy(heart);
			}
		}
	}
}