//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using Random = UnityEngine.Random;

namespace LevelCreation
{
	public class AreaInfos
	{
		public GameObject VFloor {get; set;} 
		public GameObject VRoof {get; set;} 
		public GameObject VFloorDoor {get; set;} 
		public GameObject VBlock {get; set;} 
		public GameObject VTransition {get; set;} 
		public GameObject VExit {get; set;}

		public GameObject HStart {get; set;}
        public GameObject HCrossing { get; set; }
        public GameObject HTCrossing { get; set; }
        public List<GameObject> HBlock {get; set;} 
		public GameObject HTransition {get; set;} 
		public GameObject HExit {get; set;}
        public GameObject HCorner { get; set; }

        /// <summary>
        /// Gets a HBLock entry by random
        /// </summary>
        /// <param name="noSpecials">If set to TRUE, only the default HBlock will be returned. No special Blocks</param>
        /// <returns></returns>
        public GameObject GetHBlock(bool noSpecials = false)
        {
            int borderForDefaultBlock = 19;

            int max = borderForDefaultBlock + HBlock.Count;
            int range = Random.Range(0, max);

            if (range <= borderForDefaultBlock || noSpecials)
            {
                // Return default block
                return HBlock[0];
            }
            else
            {
                // Return a special block
                return HBlock[range - borderForDefaultBlock];
            }
        }
	}
}