//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace LevelCreation
{
	public class AreaInfos
	{
		public GameObject VFloor {get; set;} 
		public GameObject VRoof {get; set;} 
		public GameObject VFloorDoor {get; set;} 
		public GameObject VBlock {get; set;} 
		public GameObject VTransition {get; set;} 
		public GameObject VExit {get; set;}

		public GameObject HFloor {get; set;} 
		public GameObject HBlock {get; set;} 
		public GameObject HTransition {get; set;} 
		public GameObject HExit {get; set;} 
	}
}