//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using Singleton;
using Player;

namespace LevelCreation
{
	public class LevelStartup : MonoBehaviour
	{
		private LevelGenerator _levelGenerator;
		public int Seed;

		/// <summary>
		/// Starts the level.
		/// </summary>
		public void StartLevel()
		{
			if (Seed > 0)
			{
				_levelGenerator = new LevelGenerator(Seed);
				_levelGenerator.CreateNewLevel();

				PrefabSingleton.Instance.Player.GetComponent<FallDamage>().ApplyNormal();
                PrefabSingleton.Instance.Player.GetComponent<PlayerUpdates>().ApplyHealth();
				PrefabSingleton.Instance.Player.transform.position = new Vector3(0, 1.813f, 0);
			}
			else
			{
				// Debug.LogError("No Seed! Level will not be creatd!");
			}
		}
	}
}