//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using Singleton;
using Player;
using System.Linq;
using Enums;

namespace LevelCreation
{
	public class LevelStartup : MonoBehaviour
	{
		private LevelGenerator _levelGenerator;
		public int Seed;

		/// <summary>
		/// Starts the level.
		/// </summary>
		public void StartLevel()
		{
			if (Seed > 0)
			{
				_levelGenerator = new LevelGenerator(Seed);
				_levelGenerator.CreateNewLevel();

                PlayerSingleton.Instance.CoinAmount = 0;
                PlayerSingleton.Instance.LevelStartDate = DateTime.Now;

				PlayerSingleton.Instance.Player.GetComponent<FallDamage>().ApplyNormal();
                PlayerSingleton.Instance.Player.GetComponent<PlayerUpdates>().ResetHealth();

                // Set Player to correct position.
                var firstBlock = CalculationSingleton.Instance.ActualCreationScope.ActualLevel[0];
                var secondBlock = CalculationSingleton.Instance.ActualCreationScope.ActualLevel[1];
                PlayerSingleton.Instance.Player.transform.position = new Vector3(firstBlock.LevelBlock.transform.position.x, 1.813f, firstBlock.LevelBlock.transform.position.z);

                if (CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection == HorzDirection.Left
                    || CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection == HorzDirection.Right)
                {
                    PlayerSingleton.Instance.Player.transform.rotation = CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection == HorzDirection.Left
                        ? Quaternion.Euler(new Vector3(0, 90, 0))
                        : Quaternion.Euler(new Vector3(0, 270, 0));
                }
                else if (CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection == HorzDirection.Forward
                    || CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection == HorzDirection.Backwards)
                {
                    PlayerSingleton.Instance.Player.transform.rotation = CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection == HorzDirection.Forward
                        ? Quaternion.Euler(new Vector3(0, 0, 0))
                        : Quaternion.Euler(new Vector3(0, 180, 0));
                }
                PlayerSingleton.Instance.FacingDirection = CalculationSingleton.Instance.ActualCreationScope.FirstHorizontalDirection;
            }
			else
			{
				// Debug.LogError("No Seed! Level will not be creatd!");
			}
		}
	}
}